# Generated by Django 5.2.15 on 2026-07-04 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='assignee_user_id',
            new_name='assignee_user',
        ),
        migrations.AlterField(
            model_name='project',
            name='customer_name',
            field=models.CharField(default='', max_length=100, verbose_name='顧客名'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(default='', max_length=100, verbose_name='案件名'),
        ),
        migrations.AlterField(
            model_name='project',
            name='note',
            field=models.TextField(blank=True, default='', verbose_name='備考'),
        ),
        migrations.AlterField(
            model_name='project',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.service', verbose_name='サービス'),
        ),
    ]
