# Generated by Django 5.2.15 on 2026-07-04 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_assignee_user_id_project_assignee_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.service', verbose_name='サービス'),
        ),
    ]
