# Generated by Django 5.2.15 on 2026-07-05 04:58

import base.models.project_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_project_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.CharField(default=base.models.project_models.create_id, editable=False, max_length=20, primary_key=True, serialize=False),
        ),
    ]
