# Generated by Django 5.2.15 on 2026-07-05 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_project_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='service',
            name='slug',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
