# Generated by Django 5.2.15 on 2026-07-05 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_service_name_alter_service_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='id',
            new_name='project_id',
        ),
    ]
