# Generated by Django 5.2.15 on 2026-07-05 06:28

import base.models.project_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_rename_id_project_project_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='登録日時'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=100, verbose_name='案件名'),
        ),
        migrations.AlterField(
            model_name='project',
            name='note',
            field=models.TextField(blank=True, verbose_name='備考'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_id',
            field=models.CharField(default=base.models.project_models.create_id, editable=False, max_length=20, primary_key=True, serialize=False, verbose_name='案件ID'),
        ),
        migrations.AlterField(
            model_name='project',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日時'),
        ),
    ]
