# Generated by Django 5.2.15 on 2026-07-05 07:14

import base.models.cost_estimate_models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_project_created_at_alter_project_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostEstimate',
            fields=[
                ('cost_estimate_id', models.CharField(default=base.models.cost_estimate_models.create_id, editable=False, max_length=20, primary_key=True, serialize=False, verbose_name='原価見積ID')),
                ('title', models.CharField(max_length=100, verbose_name='件名')),
                ('vendor_name', models.CharField(max_length=100, verbose_name='仕入先')),
                ('quote_date', models.DateField(verbose_name='見積日')),
                ('expiration_date', models.DateField(verbose_name='有効期限')),
                ('subtotal', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='小計')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=10.0, max_digits=4, verbose_name='消費税率')),
                ('tax_amount', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='消費税')),
                ('total_amount', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='合計')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='cost_estimates/', verbose_name='PDFファイル')),
                ('note', models.TextField(blank=True, verbose_name='備考')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.project', verbose_name='案件')),
            ],
        ),
        migrations.CreateModel(
            name='CostEstimateLine',
            fields=[
                ('cost_estimate_line_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='原価見積明細ID')),
                ('display_order', models.PositiveIntegerField(default=1, verbose_name='表示順')),
                ('item_name', models.CharField(max_length=100, verbose_name='品目')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='数量')),
                ('unit', models.CharField(max_length=20, verbose_name='単位')),
                ('unit_price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='単価')),
                ('amount', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='金額')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('cost_estimate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='base.costestimate', verbose_name='原価見積')),
            ],
        ),
    ]
