# Generated by Django 5.2.15 on 2026-07-05 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_costestimate_costestimateline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costestimate',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=4, verbose_name='税率'),
        ),
    ]
