# Generated by Django 5.2.15 on 2026-07-05 13:08

import base.models.cost_estimate_models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_costestimate_tax_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costestimate',
            name='cost_estimate_id',
            field=models.CharField(default=base.models.cost_estimate_models.create_id, editable=False, max_length=20, primary_key=True, serialize=False, verbose_name='原価ID'),
        ),
        migrations.AlterField(
            model_name='costestimateline',
            name='cost_estimate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='base.costestimate', verbose_name='原価'),
        ),
        migrations.AlterField(
            model_name='costestimateline',
            name='cost_estimate_line_id',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='原価明細ID'),
        ),
    ]
