# Generated by Django 5.2.15 on 2026-07-08 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_costestimate_cost_estimate_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costestimateline',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='数量'),
        ),
    ]
