# Generated by Django 5.2.15 on 2026-07-10 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_costestimateline_quantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='costestimateline',
            options={'ordering': ['display_order']},
        ),
        migrations.RemoveField(
            model_name='costestimate',
            name='subtotal',
        ),
        migrations.RemoveField(
            model_name='costestimate',
            name='tax_amount',
        ),
        migrations.RemoveField(
            model_name='costestimate',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='costestimateline',
            name='amount',
        ),
        migrations.AlterField(
            model_name='costestimate',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_estimates', to='base.project', verbose_name='案件'),
        ),
    ]
