# Generated by Django 5.2.15 on 2026-07-10 23:06

import base.models.estimate_models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_costestimateline_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estimate',
            fields=[
                ('estimate_id', models.CharField(default=base.models.estimate_models.create_id, editable=False, max_length=20, primary_key=True, serialize=False, verbose_name='見積ID')),
                ('title', models.CharField(max_length=100, verbose_name='件名')),
                ('quote_date', models.DateField(verbose_name='見積日')),
                ('expiration_date', models.DateField(verbose_name='有効期限')),
                ('status', models.CharField(choices=[('draft', '下書き'), ('rejected', '却下'), ('approved', '承認済み'), ('submitted', '提出済み'), ('won', '受注'), ('lost', '失注')], default='draft', max_length=20, verbose_name='ステータス')),
                ('note', models.TextField(blank=True, verbose_name='備考')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=10.0, max_digits=4, verbose_name='税率')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estimates', to='base.project', verbose_name='案件')),
            ],
        ),
        migrations.CreateModel(
            name='EstimateLine',
            fields=[
                ('estimate_line_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='見積明細ID')),
                ('display_order', models.PositiveIntegerField(default=1, verbose_name='表示順')),
                ('item_name', models.CharField(max_length=100, verbose_name='品目')),
                ('quantity', models.PositiveIntegerField(verbose_name='数量')),
                ('unit', models.CharField(max_length=20, verbose_name='単位')),
                ('unit_price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='単価')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('estimate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='base.estimate', verbose_name='見積')),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
    ]
