# Generated by Django 5.2.15 on 2026-07-11 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_estimate_estimateline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costestimate',
            name='tax_rate',
            field=models.PositiveIntegerField(default=10, verbose_name='税率'),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='tax_rate',
            field=models.PositiveIntegerField(default=10, verbose_name='税率'),
        ),
    ]
