# Generated by Django 5.2.15 on 2026-07-11 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_costestimate_tax_rate_alter_estimate_tax_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='cost_estimate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='estimates', to='base.costestimate', verbose_name='原価見積'),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='status',
            field=models.CharField(choices=[('draft', '下書き'), ('rejected', '却下'), ('approved', '承認済み'), ('submitted', '提出中'), ('won', '受注'), ('lost', '失注')], default='draft', max_length=20, verbose_name='ステータス'),
        ),
    ]
