# Generated by Django 5.2.15 on 2026-07-11 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_estimate_cost_estimate_alter_estimate_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='cost_estimate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='estimates', to='base.costestimate', verbose_name='原価'),
        ),
    ]
