# Generated by Django 5.2.15 on 2026-07-17 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_alter_estimate_cost_estimate'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='estimate_number',
            field=models.CharField(default='', max_length=20, unique=True, verbose_name='見積番号'),
            preserve_default=False,
        ),
    ]
